# Generated by Django 3.1 on 2020-08-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="competitions",
        ),
        migrations.AddField(
            model_name="competition",
            name="teams",
            field=models.ManyToManyField(to="football.Team"),
        ),
    ]
