# Generated by Django 3.1 on 2020-08-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0003_auto_20200826_1502"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stadium",
            name="team",
        ),
        migrations.AddField(
            model_name="team",
            name="stadium",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="football.stadium",
            ),
        ),
    ]
